const faqInfo = [
    {
        id: 1,
        title: "General Help",
        idNameLink1: "#general1",
        idNameLink2: "#general2",
        idNameLink3: "#general3",
        idNameLink4: "#general4",
        idNameLink5: "#general5",
        idNameLink6: "#general6",
        idNameLink7: "#general7",
        idNameLink8: "#general8",
        idNameLink9: "#general9",
        idNameLink10: "#general10",
        idName1: "general1",
        idName2: "general2",
        idName3: "general3",
        idName4: "general4",
        idName5: "general5",
        idName6: "general6",
        idName7: "general7",
        idName8: "general8",
        idName9: "general9",
        idName10: "general10"
    },
    {
        id: 2,
        title: "Appointments",
        idNameLink1: "#appoint1",
        idNameLink2: "#appoint2",
        idNameLink3: "#appoint3",
        idNameLink4: "#appoint4",
        idNameLink5: "#appoint5",
        idNameLink6: "#appoint6",
        idNameLink7: "#appoint7",
        idNameLink8: "#appoint8",
        idNameLink9: "#appoint9",
        idNameLink10: "#appoint10",
        idName1: "appoint1",
        idName2: "appoint2",
        idName3: "appoint3",
        idName4: "appoint4",
        idName5: "appoint5",
        idName6: "appoint6",
        idName7: "appoint7",
        idName8: "appoint8",
        idName9: "appoint9",
        idName10: "appoint10"
    },
    {
        id: 3,
        title: "My Account",
        idNameLink1: "#acc1",
        idNameLink2: "#acc2",
        idNameLink3: "#acc3",
        idNameLink4: "#acc4",
        idNameLink5: "#acc5",
        idNameLink6: "#acc6",
        idNameLink7: "#acc7",
        idNameLink8: "#acc8",
        idNameLink9: "#acc9",
        idNameLink10: "#acc10",
        idName1: "acc1",
        idName2: "acc2",
        idName3: "acc3",
        idName4: "acc4",
        idName5: "acc5",
        idName6: "acc6",
        idName7: "acc7",
        idName8: "acc8",
        idName9: "acc9",
        idName10: "acc10"
    },
    {
        id: 4,
        title: "Payments",
        idNameLink1: "#payment1",
        idNameLink2: "#payment2",
        idNameLink3: "#payment3",
        idNameLink4: "#payment4",
        idNameLink5: "#payment5",
        idNameLink6: "#payment6",
        idNameLink7: "#payment7",
        idNameLink8: "#payment8",
        idNameLink9: "#payment9",
        idNameLink10: "#payment10",
        idName1: "payment1",
        idName2: "payment2",
        idName3: "payment3",
        idName4: "payment4",
        idName5: "payment5",
        idName6: "payment6",
        idName7: "payment7",
        idName8: "payment8",
        idName9: "payment9",
        idName10: "payment10"
    },
    {
        id: 5,
        title: "Cancellations",
        idNameLink1: "#cancel1",
        idNameLink2: "#cancel2",
        idNameLink3: "#cancel3",
        idNameLink4: "#cancel4",
        idNameLink5: "#cancel5",
        idNameLink6: "#cancel6",
        idNameLink7: "#cancel7",
        idNameLink8: "#cancel8",
        idNameLink9: "#cancel9",
        idNameLink10: "#cancel10",
        idName1: "cancel1",
        idName2: "cancel2",
        idName3: "cancel3",
        idName4: "cancel4",
        idName5: "cancel5",
        idName6: "cancel6",
        idName7: "cancel7",
        idName8: "cancel8",
        idName9: "cancel9",
        idName10: "cancel10"
    },
    {
        id: 6,
        title: "Referral Rewards",
        idNameLink1: "#refer1",
        idNameLink2: "#refer2",
        idNameLink3: "#refer3",
        idNameLink4: "#refer4",
        idNameLink5: "#refer5",
        idNameLink6: "#refer6",
        idNameLink7: "#refer7",
        idNameLink8: "#refer8",
        idNameLink9: "#refer9",
        idNameLink10: "#refer10",
        idName1: "refer1",
        idName2: "refer2",
        idName3: "refer3",
        idName4: "refer4",
        idName5: "refer5",
        idName6: "refer6",
        idName7: "refer7",
        idName8: "refer8",
        idName9: "refer9",
        idName10: "refer10"
    },
    {
        id: 7,
        title: "Security",
        idNameLink1: "#secu1",
        idNameLink2: "#secu2",
        idNameLink3: "#secu3",
        idNameLink4: "#secu4",
        idNameLink5: "#secu5",
        idNameLink6: "#secu6",
        idNameLink7: "#secu7",
        idNameLink8: "#secu8",
        idNameLink9: "#secu9",
        idNameLink10: "#secu10",
        idName1: "secu1",
        idName2: "secu2",
        idName3: "secu3",
        idName4: "secu4",
        idName5: "secu5",
        idName6: "secu6",
        idName7: "secu7",
        idName8: "secu8",
        idName9: "secu9",
        idName10: "secu10"
    },
    {
        id: 8,
        title: "Accounting",
        idNameLink1: "#account1",
        idNameLink2: "#account2",
        idNameLink3: "#account3",
        idNameLink4: "#account4",
        idNameLink5: "#account5",
        idNameLink6: "#account6",
        idNameLink7: "#account7",
        idNameLink8: "#account8",
        idNameLink9: "#account9",
        idNameLink10: "#account10",
        idName1: "account1",
        idName2: "account2",
        idName3: "account3",
        idName4: "account4",
        idName5: "account5",
        idName6: "account6",
        idName7: "account7",
        idName8: "account8",
        idName9: "account9",
        idName10: "account10"
    },
    {
        id: 9,
        title: "Case",
        idNameLink1: "#case1",
        idNameLink2: "#case2",
        idNameLink3: "#case3",
        idNameLink4: "#case4",
        idNameLink5: "#case5",
        idNameLink6: "#case6",
        idNameLink7: "#case7",
        idNameLink8: "#case8",
        idNameLink9: "#case9",
        idNameLink10: "#case10",
        idName1: "case1",
        idName2: "case2",
        idName3: "case3",
        idName4: "case4",
        idName5: "case5",
        idName6: "case6",
        idName7: "case7",
        idName8: "case8",
        idName9: "case9",
        idName10: "case10"
    },
    {
        id: 10,
        title: "Client Portal",
        idNameLink1: "#cl1",
        idNameLink2: "#cl2",
        idNameLink3: "#cl3",
        idNameLink4: "#cl4",
        idNameLink5: "#cl5",
        idNameLink6: "#cl6",
        idNameLink7: "#cl7",
        idNameLink8: "#cl8",
        idNameLink9: "#cl9",
        idNameLink10: "#cl10",
        idName1: "cl1",
        idName2: "cl2",
        idName3: "cl3",
        idName4: "cl4",
        idName5: "cl5",
        idName6: "cl6",
        idName7: "cl7",
        idName8: "cl8",
        idName9: "cl9",
        idName10: "cl10"
    },
    {
        id: 11,
        title: "Merchant Portal",
        idNameLink1: "#mer1",
        idNameLink2: "#mer2",
        idNameLink3: "#mer3",
        idNameLink4: "#mer4",
        idNameLink5: "#mer5",
        idNameLink6: "#mer6",
        idNameLink7: "#mer7",
        idNameLink8: "#mer8",
        idNameLink9: "#mer9",
        idNameLink10: "#mer10",
        idName1: "mer1",
        idName2: "mer2",
        idName3: "mer3",
        idName4: "mer4",
        idName5: "mer5",
        idName6: "mer6",
        idName7: "mer7",
        idName8: "mer8",
        idName9: "mer9",
        idName10: "mer10"
    },
    {
        id: 12,
        title: "Document",
        idNameLink1: "#doc1",
        idNameLink2: "#doc2",
        idNameLink3: "#doc3",
        idNameLink4: "#doc4",
        idNameLink5: "#doc5",
        idNameLink6: "#doc6",
        idNameLink7: "#doc7",
        idNameLink8: "#doc8",
        idNameLink9: "#doc9",
        idNameLink10: "#doc10",
        idName1: "doc1",
        idName2: "doc2",
        idName3: "doc3",
        idName4: "doc4",
        idName5: "doc5",
        idName6: "doc6",
        idName7: "doc7",
        idName8: "doc8",
        idName9: "doc9",
        idName10: "doc10"
    },
    {
        id: 13,
        title: "Integrations",
        idNameLink1: "#int1",
        idNameLink2: "#int2",
        idNameLink3: "#int3",
        idNameLink4: "#int4",
        idNameLink5: "#int5",
        idNameLink6: "#int6",
        idNameLink7: "#int7",
        idNameLink8: "#int8",
        idNameLink9: "#int9",
        idNameLink10: "#int10",
        idName1: "int1",
        idName2: "int2",
        idName3: "int3",
        idName4: "int4",
        idName5: "int5",
        idName6: "int6",
        idName7: "int7",
        idName8: "int8",
        idName9: "int9",
        idName10: "int10"
    },
    {
        id: 14,
        title: "Communications",
        idNameLink1: "#com1",
        idNameLink2: "#com2",
        idNameLink3: "#com3",
        idNameLink4: "#com4",
        idNameLink5: "#com5",
        idNameLink6: "#com6",
        idNameLink7: "#com7",
        idNameLink8: "#com8",
        idNameLink9: "#com9",
        idNameLink10: "#com10",
        idName1: "com1",
        idName2: "com2",
        idName3: "com3",
        idName4: "com4",
        idName5: "com5",
        idName6: "com6",
        idName7: "com7",
        idName8: "com8",
        idName9: "com9",
        idName10: "com10"
    },
    {
        id: 15,
        title: "Tasks",
        idNameLink1: "#task1",
        idNameLink2: "#task2",
        idNameLink3: "#task3",
        idNameLink4: "#task4",
        idNameLink5: "#task5",
        idNameLink6: "#task6",
        idNameLink7: "#task7",
        idNameLink8: "#task8",
        idNameLink9: "#task9",
        idNameLink10: "#task10",
        idName1: "task1",
        idName2: "task2",
        idName3: "task3",
        idName4: "task4",
        idName5: "task5",
        idName6: "task6",
        idName7: "task7",
        idName8: "task8",
        idName9: "task9",
        idName10: "task10"
    },
    {
        id: 16,
        title: "Workflow",
        idNameLink1: "#work1",
        idNameLink2: "#work2",
        idNameLink3: "#work3",
        idNameLink4: "#work4",
        idNameLink5: "#work5",
        idNameLink6: "#work6",
        idNameLink7: "#work7",
        idNameLink8: "#work8",
        idNameLink9: "#work9",
        idNameLink10: "#work10",
        idName1: "work1",
        idName2: "work2",
        idName3: "work3",
        idName4: "work4",
        idName5: "work5",
        idName6: "work6",
        idName7: "work7",
        idName8: "work8",
        idName9: "work9",
        idName10: "work10"
    },
    {
        id: 17,
        title: "Website",
        idNameLink1: "#web1",
        idNameLink2: "#web2",
        idNameLink3: "#web3",
        idNameLink4: "#web4",
        idNameLink5: "#web5",
        idNameLink6: "#web6",
        idNameLink7: "#web7",
        idNameLink8: "#web8",
        idNameLink9: "#web9",
        idNameLink10: "#web10",
        idName1: "web1",
        idName2: "web2",
        idName3: "web3",
        idName4: "web4",
        idName5: "web5",
        idName6: "web6",
        idName7: "web7",
        idName8: "web8",
        idName9: "web9",
        idName10: "web10"
    },
    {
        id: 18,
        title: "E-stores",
        idNameLink1: "#sto1",
        idNameLink2: "#sto2",
        idNameLink3: "#sto3",
        idNameLink4: "#sto4",
        idNameLink5: "#sto5",
        idNameLink6: "#sto6",
        idNameLink7: "#sto7",
        idNameLink8: "#sto8",
        idNameLink9: "#sto9",
        idNameLink10: "#sto10",
        idName1: "sto1",
        idName2: "sto2",
        idName3: "sto3",
        idName4: "sto4",
        idName5: "sto5",
        idName6: "sto6",
        idName7: "sto7",
        idName8: "sto8",
        idName9: "sto9",
        idName10: "sto10"
    },
    {
        id: 19,
        title: "Leads",
        idNameLink1: "#leads1",
        idNameLink2: "#leads2",
        idNameLink3: "#leads3",
        idNameLink4: "#leads4",
        idNameLink5: "#leads5",
        idNameLink6: "#leads6",
        idNameLink7: "#leads7",
        idNameLink8: "#leads8",
        idNameLink9: "#leads9",
        idNameLink10: "#leads10",
        idName1: "leads1",
        idName2: "leads2",
        idName3: "leads3",
        idName4: "leads4",
        idName5: "leads5",
        idName6: "leads6",
        idName7: "leads7",
        idName8: "leads8",
        idName9: "leads9",
        idName10: "leads10"
    },
    {
        id: 20,
        title: "Reports",
        idNameLink1: "#report1",
        idNameLink2: "#report2",
        idNameLink3: "#report3",
        idNameLink4: "#report4",
        idNameLink5: "#report5",
        idNameLink6: "#report6",
        idNameLink7: "#report7",
        idNameLink8: "#report8",
        idNameLink9: "#report9",
        idNameLink10: "#report10",
        idName1: "report1",
        idName2: "report2",
        idName3: "report3",
        idName4: "report4",
        idName5: "report5",
        idName6: "report6",
        idName7: "report7",
        idName8: "report8",
        idName9: "report9",
        idName10: "report10"
    }
]

export default faqInfo;